import { DurableObject } from "cloudflare:workers";
import { parseClientMessage, type LogEntry, type ServerMessage } from "../../src/sync/protocol";

export type Env = {
  ROOM: DurableObjectNamespace<Room>;
};

/**
 * A room id is only ever generated by the client as a long random string. It is
 * also the only credential: anyone holding the link can write, which is the
 * intended trade for three friends and no login screen. Validating the shape
 * keeps a stray path from creating junk Durable Objects.
 */
const ROOM_ID = /^[A-Za-z0-9_-]{16,64}$/;

/**
 * How far the log may run past its last snapshot before the server asks for a
 * fresh one. A season of volleyball is a few hundred actions, so this compacts
 * roughly once a season rather than once a night.
 */
const COMPACT_AFTER = 300;

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const match = /^\/room\/([^/]+)$/.exec(url.pathname);
    if (!match) return new Response("Not found", { status: 404 });

    const roomId = match[1];
    if (!ROOM_ID.test(roomId)) return new Response("Bad room id", { status: 400 });

    if (request.headers.get("Upgrade") !== "websocket") {
      return new Response("Expected WebSocket", { status: 426 });
    }

    return env.ROOM.get(env.ROOM.idFromName(roomId)).fetch(request);
  },
} satisfies ExportedHandler<Env>;

type LogRow = { seq: number; local_id: string; action: string };

/**
 * One room: an append-only log of actions, ordered by a server-assigned `seq`.
 *
 * The server never interprets an action — it only orders, stores and fans out.
 * That is what keeps it small: all the volleyball logic stays in the client
 * reducer, and the two cannot drift apart.
 */
export class Room extends DurableObject<Env> {
  private nextSeq = 0;
  /** Seq of the oldest entry still held. Everything before it was compacted. */
  private baseSeq = 0;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    ctx.blockConcurrencyWhile(async () => {
      const sql = this.ctx.storage.sql;
      sql.exec(
        "CREATE TABLE IF NOT EXISTS log (seq INTEGER PRIMARY KEY, local_id TEXT NOT NULL, action TEXT NOT NULL)",
      );
      // Dedupes a resend from a client that reconnected before its append was
      // acknowledged. Kept across compaction so a very stale phone cannot
      // reintroduce a match that was already folded into a snapshot.
      sql.exec("CREATE TABLE IF NOT EXISTS seen (local_id TEXT PRIMARY KEY, seq INTEGER NOT NULL)");
      sql.exec("CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value INTEGER NOT NULL)");

      const max = sql.exec("SELECT COALESCE(MAX(seq), -1) AS m FROM log").one().m as number;
      this.nextSeq = max + 1;
      const base = sql.exec("SELECT value FROM meta WHERE key = 'baseSeq'").toArray();
      this.baseSeq = base.length > 0 ? (base[0].value as number) : 0;
    });

    // Keepalive that never wakes the object from hibernation.
    this.ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair("ping", "pong"));
  }

  async fetch(_request: Request): Promise<Response> {
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair);
    // Hibernatable: the room can be evicted between matches without dropping
    // anyone's connection, which is most of why this costs nothing to run.
    this.ctx.acceptWebSocket(server);
    return new Response(null, { status: 101, webSocket: client });
  }

  async webSocketMessage(ws: WebSocket, raw: string | ArrayBuffer): Promise<void> {
    if (typeof raw !== "string") return;

    let message;
    try {
      message = parseClientMessage(raw);
    } catch {
      this.reply(ws, { type: "error", message: "Malformed message" });
      return;
    }

    switch (message.type) {
      case "hello":
        this.catchUp(ws, message.since);
        return;
      case "append":
        this.append(message.localId, message.action);
        return;
      case "compact":
        this.compact(message.atSeq, message.state);
        return;
    }
  }

  /**
   * `reset` tells the client to replay from an empty state. It is set whenever
   * the client is asking for something at or before the oldest entry held, since
   * anything older no longer exists as an individual entry.
   */
  private catchUp(ws: WebSocket, since: number): void {
    const rows = this.ctx.storage.sql
      .exec<LogRow>("SELECT seq, local_id, action FROM log WHERE seq >= ? ORDER BY seq", since)
      .toArray();

    this.reply(ws, {
      type: "sync",
      reset: since <= this.baseSeq,
      entries: rows.map(toEntry),
    });
  }

  private append(localId: string, action: unknown): void {
    const sql = this.ctx.storage.sql;
    if (sql.exec("SELECT 1 FROM seen WHERE local_id = ?", localId).toArray().length > 0) return;

    const seq = this.nextSeq++;
    const serialised = JSON.stringify(action);
    sql.exec("INSERT INTO log (seq, local_id, action) VALUES (?, ?, ?)", seq, localId, serialised);
    sql.exec("INSERT INTO seen (local_id, seq) VALUES (?, ?)", localId, seq);

    this.broadcast({ type: "entry", entry: { seq, localId, action: action as LogEntry["action"] } });

    if (seq - this.baseSeq > COMPACT_AFTER) {
      // Asked of everyone; whichever client is caught up with nothing pending
      // answers, and a stale `atSeq` is rejected below.
      this.broadcast({ type: "need-compaction", atSeq: seq });
    }
  }

  /**
   * Replace the whole log with a single snapshot entry.
   *
   * Rejecting a stale `atSeq` is what makes this safe: if anything was appended
   * between the client folding its snapshot and this message arriving, the
   * snapshot does not account for it and collapsing the log would lose it.
   */
  private compact(atSeq: number, state: unknown): void {
    if (atSeq !== this.nextSeq - 1) return;

    const sql = this.ctx.storage.sql;
    const snapshot: LogEntry["action"] = { type: "replace-state", state } as LogEntry["action"];
    sql.exec("DELETE FROM log");
    sql.exec(
      "INSERT INTO log (seq, local_id, action) VALUES (?, ?, ?)",
      atSeq,
      "snapshot-" + atSeq,
      JSON.stringify(snapshot),
    );
    sql.exec(
      "INSERT INTO meta (key, value) VALUES ('baseSeq', ?) ON CONFLICT(key) DO UPDATE SET value = ?",
      atSeq,
      atSeq,
    );
    this.baseSeq = atSeq;

    this.broadcast({
      type: "sync",
      reset: true,
      entries: [{ seq: atSeq, localId: "snapshot-" + atSeq, action: snapshot }],
    });
  }

  private broadcast(message: ServerMessage): void {
    const payload = JSON.stringify(message);
    for (const socket of this.ctx.getWebSockets()) {
      try {
        socket.send(payload);
      } catch {
        // A socket that died between the fan-out and here reconnects on its own.
      }
    }
  }

  private reply(ws: WebSocket, message: ServerMessage): void {
    try {
      ws.send(JSON.stringify(message));
    } catch {
      // Same as above: the client's reconnect path re-requests what it missed.
    }
  }
}

function toEntry(row: LogRow): LogEntry {
  return { seq: row.seq, localId: row.local_id, action: JSON.parse(row.action) };
}
